version: '3.7'

services:
  hyphaircoiff-nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: hyphaircoiff-nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
      # Used to authentify access
      - /etc/nginx/htpasswd:/etc/nginx/htpasswd:ro

  hyphaircoiff-nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: hyphaircoiff-nginx-proxy-letsencrypt
    restart: always
    environment:
      DEFAULT_EMAIL: "contact@${DOMAIN}"
      NGINX_PROXY_CONTAINER: hyphaircoiff-nginx-proxy
      DEBUG: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

networks:
  default:
    external:
      name: hypaircoif

volumes:
  .:
  certs:
  html:
  vhostd:
